### ISSUE TITLE
What is the paper for `dorder` used in this benchmark

### ISSUE THREAD

**Issue by arbipher** [hopv/benchmarks#2]
Thanks!

**Comment by AdrienChampion** [comment]
These benchmarks wet setup for this 2018 paper
- https://link.springer.com/chapter/10.1007/978-3-030-02768-1_8

I assume we used whatever was the most recent back then.

@ryosu-sato or @naokikob might be able to provide more precise and trustworthy information 😸

**Comment by naokikob** [comment]
DOrder is the name of the tool reported in the paper:
```
He Zhu, Gustavo Petri, Suresh Jagannathan:
Automatically learning shape specifications. PLDI 2016: 491-507
```

I think the benchmark came from that paper and:
```
He Zhu, Aditya V. Nori, Suresh Jagannathan:
Learning refinement types. ICFP 2015: 400-411

**Comment by arbipher** [comment]
Thank you all! I think the papers are correct.
